#!/usr/bin/env bash

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd)

# shellcheck disable=SC1090
source "$ROOT_DIR/compose-common"
export TZ
export USER_UID
export USER_GID

docker compose -p ddrm-bot -f "$ROOT_DIR/docker-compose.bot.yml" "$@"
