#!/usr/bin/env bash
# shellcheck disable=SC1090

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd)
ENV_LOCAL="$ROOT_DIR/.env.local"

if [[ -f "$ENV_LOCAL" ]]; then
    TZ=$(source "$ENV_LOCAL" && echo "$TZ")
    USER_UID=$(source "$ENV_LOCAL" && echo "$USER_UID")
    USER_GID=$(source "$ENV_LOCAL" && echo "$USER_GID")
fi

if command -v timedatectl &> /dev/null; then
    TZ=${TZ:-$(timedatectl -p Timezone --value show)}
fi

USER_UID=${USER_UID:-$(id -u)}
USER_GID=${USER_GID:-$(id -g)}

export TZ
export USER_UID
export USER_GID
