#!/usr/bin/env bash

if ! command -v docker &> /dev/null; then
    opm-println-error "Not found docker command"
    exit 1
fi

NETWORK_NAME=osom-net

if docker network inspect "$NETWORK_NAME" &> /dev/null; then
    echo "Network '$NETWORK_NAME' already exists"
    exit 1
fi

echo "Create docker network: '$NETWORK_NAME'"
docker network create --driver bridge "$NETWORK_NAME"
