version: "3.3"

services:
  worker:
    image: "ghcr.io/osom8979/osom-api:latest"
    build: .
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    user: ${USER_UID:?err}:${USER_GID:?err}
    command: worker
    env_file:
      - .env.local
    deploy:
      mode: replicated
      replicas: 2
