version: "3.3"

services:
  master:
    image: "ghcr.io/osom8979/osom-api:master"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - osom-net
    user: ${USER_UID:?err}:${USER_GID:?err}
    environment:
      - "TZ=Asia/Seoul"
      - "COLORED_LOGGING=${COLORED_LOGGING:?err}"
      - "DEFAULT_LOGGING=${DEFAULT_LOGGING:?err}"
      - "SIMPLE_LOGGING=${SIMPLE_LOGGING:?err}"
      - "ROTATE_LOGGING_PREFIX=${ROTATE_LOGGING_PREFIX:?err}"
      - "ROTATE_LOGGING_WHEN=${ROTATE_LOGGING_WHEN:?err}"
      - "USE_UVLOOP=${USE_UVLOOP:?err}"
      - "SEVERITY=${SEVERITY:?err}"
      - "DEBUG=${DEBUG:?err}"
      - "VERBOSE=${VERBOSE:?err}"
      - "HTTP_HOST=${HTTP_HOST:?err}"
      - "HTTP_PORT=${HTTP_PORT:?err}"
      - "HTTP_TIMEOUT=${HTTP_TIMEOUT:?err}"
      - "REDIS_HOST=${REDIS_HOST:?err}"
      - "REDIS_PORT=${REDIS_PORT:?err}"
      - "REDIS_TIMEOUT=${REDIS_TIMEOUT:?err}"
      - "REDIS_DATABASE=${REDIS_DATABASE:?err}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD:?err}"
      - "REDIS_USE_TLS=False"
      - "REDIS_CONNECTION_TIMEOUT=${REDIS_CONNECTION_TIMEOUT:?err}"
      - "REDIS_SUBSCRIBE_TIMEOUT=${REDIS_SUBSCRIBE_TIMEOUT:?err}"
      - "S3_ENDPOINT=${S3_ENDPOINT:?err}"
      - "S3_ACCESS=${S3_ACCESS:?err}"
      - "S3_SECRET=${S3_SECRET:?err}"
      - "S3_REGION=${S3_REGION:?err}"
      - "S3_BUCKET=${S3_BUCKET:?err}"
      - "SUPABASE_URL=${SUPABASE_URL:?err}"
      - "SUPABASE_KEY=${SUPABASE_KEY:?err}"
      - "TELEGRAM_TOKEN=${TELEGRAM_TOKEN:?err}"
    command: bot

networks:
  osom-net:
    external: true
