#!/usr/bin/env bash

if ! command -v sed &> /dev/null; then
    opm-println-error "Not found sed command"
    exit 1
fi
if ! command -v openssl &> /dev/null; then
    opm-println-error "Not found openssl command"
    exit 1
fi

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd)
ENV_SRC="$ROOT_DIR/env-template"
ENV_DEST="$ROOT_DIR/.env"

if [[ ! -f "$ENV_DEST" ]]; then
    echo "Generate an environment file: $ENV_DEST"
    sed -e "s/@USER_UID@/$(id -u)/g" \
        -e "s/@USER_GID@/$(id -g)/g" \
        -e "s/@REDIS_PASSWORD@/$(openssl rand -hex 32)/g" \
        "$ENV_SRC" > "$ENV_DEST"
fi
