#!/usr/bin/env bash

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd)
ENV_LOCAL="$ROOT_DIR/.env.local"

if ! command -v timedatectl &> /dev/null; then
    echo "Not found timedatectl command" 1>&2
    exit 1
fi

if ! CURRENT_TIMEZONE=$(timedatectl -p Timezone --value show); then
    echo "The 'timedatectl' command occurred error code $?" 1>&2
    exit 1
fi

if ! command -v opm-vault &> /dev/null; then
    echo "Not found opm-vault command" 1>&2
    exit 1
fi

if ! opm-vault has api; then
    echo "Key 'api' does not exist in opm-vault" 1>&2
    exit 1
fi

if ! opm-vault has web; then
    echo "Key 'web' does not exist in opm-vault" 1>&2
    exit 1
fi

ENV_CONTENT="
# ================================================
# Created at $(date)
TZ=${CURRENT_TIMEZONE}
USER_UID=$(id -u)
USER_GID=$(id -g)

# vault api
$(opm-vault request api)

# vault web
$(opm-vault request web)
# ================================================
"

echo "$ENV_CONTENT" >> "$ENV_LOCAL"
